language: d
d: dmd

before_install:
    # - sudo add-apt-repository --yes ppa:tobydox/mingw-w64
    - sudo add-apt-repository --yes ppa:tobydox/mingw-x-trusty
    - sudo apt-get -qq update
    - sudo apt-get install -y gcc-multilib libevent-dev mingw32-x-gcc mingw32-x-binutils
    - .travis/build-win32.sh before_install



script:
    - |
        mkdir linux-x86
        mkdir linux-x86_64
        mkdir win-x86

    - |
        cd nwn-stagingtool

        make GCCFLAGS=-m32
        dub build --arch=x86 -b release
        mv nwn-stagingtool ../linux-x86/

        make GCCFLAGS=-m64
        dub build --arch=x86_64 -b release
        mv nwn-stagingtool ../linux-x86_64/

        export PATH=/opt/mingw32/bin:/usr/i586-mingw32msvc/bin:$PATH
        make win-x86
        .travis/build-win32.sh exec dub build --arch=x86 -b release
        mv nwn-stagingtool.exe ../win-x86/nwn-stagingtool

        cd ..
