language: d
d: dmd

before_install:
    # Install packages
    - sudo apt-get install -y gcc-multilib zip
    # Setup windows compilers
    - >
        .travis/build-win.sh before_install
        && source .travis/build-win.sh
    # Register nwn-lib-d
    - >
        git clone https://github.com/CromFr/nwn-lib-d.git ../nwn-lib-d
        && dub add-local ../nwn-lib-d
        && wine dub add-local ../nwn-lib-d



script:
    - >
        source .travis/build-win.sh
        && mkdir -p bin/{linux,win}-x86{,_64}

    # nwn2-stagingtool
    - >
        cd stagingtool
        && make CFLAGS="-m32" LDFLAGS="-melf_i386"
        && dub build --arch=x86 -b release
        && mv nwn2-stagingtool ../bin/linux-x86/
        && cd ..
    - >
        cd stagingtool
        && make CFLAGS="-m64"
        && dub build --arch=x86_64 -b release
        && mv nwn2-stagingtool ../bin/linux-x86_64/
        && cd ..
    - >
        cd stagingtool
        && wine dub build --arch=x86 -b release
        && mv nwn2-stagingtool.exe ../bin/win-x86/nwn2-stagingtool
        && cd ..
    - >
        cd stagingtool
        && wine dub build --arch=x86_64 -b release
        && mv nwn2-stagingtool.exe ../bin/win-x86_64/nwn2-stagingtool
        && cd ..

    # nwn2-moduleinstaller
    - >
        cd moduleinstaller
        && dub build --arch=x86 -b release
        && mv nwn2-moduleinstaller ../bin/linux-x86/
        && cd ..
    - >
        cd moduleinstaller
        && dub build --arch=x86_64 -b release
        && mv nwn2-moduleinstaller ../bin/linux-x86_64/
        && cd ..
    - >
        cd moduleinstaller
        && wine dub build --arch=x86 -b release
        && mv nwn2-moduleinstaller.exe ../bin/win-x86/nwn2-moduleinstaller
        && cd ..
    - >
        cd moduleinstaller
        && wine dub build --arch=x86_64 -b release
        && mv nwn2-moduleinstaller.exe ../bin/win-x86_64/nwn2-moduleinstaller
        && cd ..

    # nwn2-itemupdater
    - >
        cd itemupdater
        && dub build --arch=x86 -b release
        && mv nwn2-itemupdater ../bin/linux-x86/
        && cd ..
    - >
        cd itemupdater
        && dub build --arch=x86_64 -b release
        && mv nwn2-itemupdater ../bin/linux-x86_64/
        && cd ..
    - >
        cd itemupdater
        && wine dub build --arch=x86 -b release
        && mv nwn2-itemupdater.exe ../bin/win-x86/nwn2-itemupdater
        && cd ..
    # - >
    #     cd itemupdater
    #     && wine dub build --arch=x86_64 -b release
    #     && mv nwn2-itemupdater.exe ../bin/win-x86_64/nwn2-itemupdater
    #     && cd ..

    # nwn2-cam-to-sql
    - >
        cd cam-to-sql
        && dub build --arch=x86 -b release
        && dub build --arch=x86 -b release :upgrade-scripts
        && tar cvz nwn2-cam-to-sql.tar.gz nwn2-cam-to-sql nwn2-cam-to-sql-upgrade-scripts
        && mv nwn2-cam-to-sql.tar.gz ../bin/linux-x86/
        && cd ..
    - >
        cd cam-to-sql
        && dub build --arch=x86_64 -b release
        && dub build --arch=x86_64 -b release :upgrade-scripts
        && tar cvz nwn2-cam-to-sql.tar.gz nwn2-cam-to-sql nwn2-cam-to-sql-upgrade-scripts
        && mv nwn2-cam-to-sql.tar.gz ../bin/linux-x86_64/
        && cd ..
    - >
        cd cam-to-sql
        && wine dub build --arch=x86 -b release
        && wine dub build --arch=x86 -b release :upgrade-scripts
        && zip nwn2-cam-to-sql.zip cam-to-sql.exe cam-to-sql-upgrade-scripts.exe
        && mv nwn2-cam-to-sql.zip ../bin/win-x86/nwn2-cam-to-sql
        && cd ..
    - >
        cd cam-to-sql
        && wine dub build --arch=x86_64 -b release
        && wine dub build --arch=x86_64 -b release :upgrade-scripts
        && zip nwn2-cam-to-sql.zip cam-to-sql.exe cam-to-sql-upgrade-scripts.exe
        && mv nwn2-cam-to-sql.exe ../bin/win-x86_64/nwn2-cam-to-sql
        && cd ..

after_success:
    - .travis/gh-pages.sh

