language: d
d: dmd

before_install:
    # - sudo add-apt-repository --yes ppa:tobydox/mingw-w64
    - sudo add-apt-repository --yes ppa:tobydox/mingw-x-trusty
    - sudo apt-get -qq update
    - sudo apt-get install -y gcc-multilib mingw32-x-gcc mingw32-x-binutils
    - .travis/build-win32.sh before_install
    - git clone https://github.com/CromFr/nwn-lib-d.git ../nwn-lib-d
    - dub add-local ../nwn-lib-d
    - .travis/build-win32.sh exec dub add-local ../nwn-lib-d



script:
    # nwn2-stagingtool
    - >
        mkdir linux-x86
        && mkdir linux-x86_64
        && mkdir win-x86
    - >
        cd stagingtool
        && make GCCFLAGS="-m32" LDFLAGS="-melf_i386"
        && dub build --arch=x86 -b release
        && mv nwn2-stagingtool ../linux-x86/
        && cd ..
    - >
        cd stagingtool
        && make GCCFLAGS="-m64"
        && dub build --arch=x86_64 -b release
        && mv nwn2-stagingtool ../linux-x86_64/
        && cd ..
    - >
        cd stagingtool
        && OLDPATH=$PATH
        && export PATH=/opt/mingw32/bin:/usr/i586-mingw32msvc/bin:$PATH
        && make win-x86
        && ../.travis/build-win32.sh exec dub build --arch=x86 -b release
        && mv nwn2-stagingtool.exe ../win-x86/nwn2-stagingtool
        && export PATH=$OLDPATH
        && cd ..

