language: d
d: dmd

before_install:
    # Install packages
    - sudo apt-get install -y gcc-multilib
    # Setup windows compilers
    - >
        .travis/build-win32.sh before_install
        && source .travis/build-win32.sh
    # Register nwn-lib-d
    - >
        git clone https://github.com/CromFr/nwn-lib-d.git ../nwn-lib-d
        && dub add-local ../nwn-lib-d
        && wine dub add-local ../nwn-lib-d



script:
    # nwn2-stagingtool
    - >
        source .travis/build-win32.sh
        && mkdir linux-x86
        && mkdir linux-x86_64
        && mkdir win-x86
    - >
        cd stagingtool
        && make GCCFLAGS="-m32" LDFLAGS="-melf_i386"
        && dub build --arch=x86 -b release
        && mv nwn2-stagingtool ../linux-x86/
        && cd ..
    - >
        cd stagingtool
        && make GCCFLAGS="-m64"
        && dub build --arch=x86_64 -b release
        && mv nwn2-stagingtool ../linux-x86_64/
        && cd ..
    - >
        cd stagingtool
        && make wine-dmc
        && wine dub build --arch=x86 -b release
        && mv nwn2-stagingtool.exe ../win-x86/nwn2-stagingtool
        && cd ..

after_success:
    - .travis/gh-pages.sh

